version: '2'
services:
  web:
    image: collinmesser/collinmesser:development
    build:
      context: ./
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
